use_stop_pose: False
num_waypoints: 6
visualization: True
speed: 0.09
turn_omega_kp: 2.2
turn_omega_max: 5.0

canonical_goal_pose_right: {
  x: 0.24,
  y: -0.24,
  theta: -1.57,
}

canonical_goal_pose_left: {
  x: 0.40,
  y: 0.40,
  theta: 1.57,
}

canonical_goal_pose_straight: {
  x: 0.50,
  y: 0.0,
  theta: 0.0,
}

debug_dir: -1
